#!/bin/sh

name="${1##*/}"
case "$name" in
	*.gz)
		tmpfile=$(mktemp -p /run/user/$UID --suffix="-${name%.*}" mimepipe-XXXXXXXXXX)
		;;
	*)
		tmpfile=$(mktemp -p /run/user/$UID --suffix="-${name%.*}" mimepipe-XXXXXXXXXX)
		;;
esac

zcat "$1" >"$tmpfile"
mimepipe "$tmpfile"
rm -f "$tmpfile"
