#!/bin/sh

if test $# -le 1; then
	echo
	exec 7za l -bso0 -bsp0 -bd -bb0 "$1"
else
	tmpdir=$(mktemp -dp /run/user/$UID mimepipe-XXXXXXXXXX)
	7za x -o"$tmpdir" -bso0 -bsp0 -bd -bb0 "$1" "$2"
	shift
	env -C "$tmpdir" mimepipe "$@"
	rm -rf "$tmpdir"
fi
