#!/bin/sh

if test $# -le 1; then
	isoinfo -l -i "$1" -find -ls
else
	tmpfile=$(mktemp -p /run/user/$UID mimepipe-XXXXXXXXXX)
	image=$(readlink -ne "$1")
	isoinfo -x "$2" -i "$image" >"$tmpfile"
	shift
	mimepipe "$tmpfile" "$@"
	rm -rf "$tmpfile"
fi
