#!/bin/sh

name="${1##*/}"
case "$name" in
	*.Z)
		tmpfile=$(mktemp -p /run/user/$UID --suffix="-${name%.*}" mimepipe-XXXXXXXXXX)
		;;
	*)
		tmpfile=$(mktemp -p /run/user/$UID --suffix="-${name%.*}" mimepipe-XXXXXXXXXX)
		;;
esac

uncompress -c "$1" >"$tmpfile"
shift
mimepipe "$tmpfile" "$@"
rm -f "$tmpfile"
