#!/bin/sh

name="${1##*/}"
case "$name" in
	*.lz)
		tmpfile=$(mktemp -p /run/user/$UID --suffix="-${name%.*}" mimepipe-XXXXXXXXXX)
		;;
	*)
		tmpfile=$(mktemp -p /run/user/$UID --suffix="-${name%.*}" mimepipe-XXXXXXXXXX)
		;;
esac

lzcat "$1" >"$tmpfile"
shift
mimepipe "$tmpfile" "$@"
rm -f "$tmpfile"
