#!/bin/sh

if test $# -le 1; then
	echo
	exec unzip -lv "$1"
else
	tmpdir=$(mktemp -dp /run/user/$UID mimepipe-XXXXXXXXXX)
	unzip -qd "$tmpdir" "$1" "$2"
	shift
	env -C "$tmpdir" mimepipe "$@"
	rm -rf "$tmpdir"
fi
