#!/bin/sh

tmpfile=$(mktemp -p /run/user/$UID --suffix="${1/*./.}" mimepipe-XXXXXXXXXX)
cat "$1" >"$tmpfile"
#lowriter --headless --convert-to html --outdir /run/user/$UID "$tmpfile" >/dev/null 2>/dev/null
unoconv -v -f html -o "${tmpfile%.*}.html" "$tmpfile" >/dev/null 2>/dev/null
echo
w3m -dump "${tmpfile%.*}.html"
rm -f "$tmpfile" "${tmpfile%.*}.html"
