name: Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
	steps:
	  - name: Checkout
	    uses: actions/checkout@v2
	  - name: Prepare
	    run: sudo apt-get install m4 make
      - name: Build
	    run: make build/obs/mimepipe.spec
	  - name: Release
	    uses: softprops/action-gh-release@v1
		if: startsWith(github.ref, 'refs/tags/v')
		with:
		  files: |
		  - build/obs/mimepipe.spec

